SELECT NAME FROM CLIENT_MASTER;

SELECT * FROM CLIENT_MASTER;

SELECT NAME, CITY, STATE FROM CLIENT_MASTER;

SELECT DISTINCT DESCRIPTION FROM PRODUCT_MASTER;

SELECT * FROM CLIENT_MASTER WHERE CITY = 'Mumbai';

SELECT SALESMANNAME FROM SALESMAN_MASTER WHERE SALAMT = 3000;

SELECT * FROM CLIENT_MASTER;
UPDATE CLIENT_MASTER SET CITY = 'Banglore' WHERE CLIENTNO = 'C00005';
SELECT * FROM CLIENT_MASTER;

SELECT * FROM CLIENT_MASTER;
UPDATE CLIENT_MASTER SET BALDUE = '1000' WHERE CLIENTNO = 'C00001';
SELECT * FROM CLIENT_MASTER;

SELECT * FROM PRODUCT_MASTER;
UPDATE PRODUCT_MASTER SET COSTPRICE = 950 WHERE DESCRIPTION = 'Trousers';
SELECT * FROM PRODUCT_MASTER;

SELECT * FROM SALESMAN_MASTER;
UPDATE SALESMAN_MASTER SET CITY = 'Pune';
SELECT * FROM SALESMAN_MASTER;

SELECT * FROM SALESMAN_MASTER;
DELETE FROM SALESMAN_MASTER WHERE SALAMT = '3500';
SELECT * FROM SALESMAN_MASTER;

SELECT * FROM PRODUCT_MASTER;
DELETE FROM PRODUCT_MASTER WHERE QTYONHAND = '100';
SELECT * FROM PRODUCT_MASTER;

SELECT * FROM CLIENT_MASTER;
DELETE FROM CLIENT_MASTER WHERE STATE = 'Tamilnadu';
SELECT * FROM CLIENT_MASTER;

DESC CLIENT_MASTER;
ALTER TABLE CLIENT_MASTER ADD COLUMN TELEPHONE INTEGER;
DESC CLIENT_MASTER;

DESC PRODUCT_MASTER;
ALTER TABLE PRODUCT_MASTER MODIFY COLUMN SELLPRICE DECIMAL(10,2);
DESC PRODUCT_MASTER;

DROP TABLE CLIENT_MASTER;
SHOW TABLES;

RENAME TABLE SALESMAN_MASTER TO SMAN_MAST;
SHOW TABLES;

ALTER TABLE CLIENT_MASTER DROP COLUMN TELEPHONE; 